### ISSUE TITLE
lab02.4 - invalid test

### ISSUE THREAD

**Issue by mintxelas** [Azure/LearnAI-Bootcamp#15]
There is a single test in the tests project that doesn´t test the EchoBot, but a similar Dialog created in the test project itself. If I try to test the one in EchoBot, it fails. If the bot framework is updated, it doesn´t compile. Could we have a working example of how to write a unit test with bot framework?

**Comment by amthomas46** [comment]
Noted that this doesn't work for v3. We've updated the labs for v4, but will probably be moving the testing/logging exercises to supplementary materials. What I can say is try cloning the whole v4 SDK, and looking at how they test their SDK. That's probably the best example that I know of at this point.
