### ISSUE TITLE
AML Workbench instructions anre never mentioned please add a section on how to install workbench

### ISSUE THREAD

**Issue by burstingninja** [Azure/LearnAI-Bootcamp#18]
https://docs.microsoft.com/en-us/azure/machine-learning/desktop-workbench/experimentation-service-configuration#running-a-script-on-a-remote-vm-targeting-user-managed-environments

Add this to the tutorial please, I had no Idea what you meant with workbench when I was doing it

**Comment by amthomas46** [comment]
Closing as we no longer cover workbench
