### ISSUE TITLE
Missing closing braces } at lab step

### ISSUE THREAD

**Issue by Manesh-R** [Azure/LearnAI-Bootcamp#27]
https://azure.github.io/LearnAI-Bootcamp/lab01.1-computer_vision/2_ImageProcessor.html

Can you also add a closing brace } at the end of step 6 code snippet?

**Comment by amthomas46** [comment]
The closing brace is in the starter code here https://github.com/Azure/LearnAI-Bootcamp/blob/master/lab01.1-computer_vision/resources/code/Starting-ImageProcessing/ProcessingLibrary/ImageProcessor.cs
