### ISSUE TITLE
Documentation points to wrong code folder

### ISSUE THREAD

**Issue by Manesh-R** [Azure/LearnAI-Bootcamp#29]
## Guide points to wrong code folder

https://azure.github.io/LearnAI-Bootcamp/lab01.2_customvision01/1_Classification_Lab.html is pointing to C:\LearnAI-Bootcamp\lab01.3_customvision02\Resources\Starter which is wrong. 

It should point to C:\LearnAI-Bootcamp\lab01.2_customvision01\Resources\Starter

## Lab 1.3 asks to copy code to Temp folder as well. 
We should say, 1.2 copy to Temp2 and 1.3 copy to Temp3. That way attendees can have both code working at the end and look through them.

## Project limit on Custom Vision and idempotency
We should modify the code such that user can re-run the program to see it working. Currently each time we are trying to create a new project. Code should be modified to create a project named 'Classification Project' if that doesn't exist. If it exists, reuse that project.

Or else ask attendee to delete the project before re-running the application. 

Minimum, we should change this from My New Project to Classification Project for 1.2

**Comment by amthomas46** [comment]
Lab 1.4 is a challenge lab. It should look similar to lab 1.2 except without any code provided. I can add the remaining items as feedback for our next cycle. Thanks!

**Comment by vayin** [comment]
I am getting the following error. Any idea?
Microsoft.Rest.HttpOperationException
  HResult=0x80131500
  Message=Operation returned an invalid status code 'BadRequest'
  Any idea why this is happening?

**Comment by vayin** [comment]
also where is the "My First Project Created"?

**Comment by vayin** [comment]
where the "My First Project" created? I am unable to find it out

**Comment by amthomas46** [comment]
Hi @vayin , thanks for reaching out. Can you provide us with additional details, like which specific lab you are on, what code is failing, any debugging you've tried, etc.?


@ctestaoneill / @ctesta-oneillmsft any ideas?

**Comment by Rodrigossz** [comment]
OMG, sorry for the huge delay. I manage a lot of repositories and this one was retired years ago. The LearnAI team has not existed since May 2019 and I only found this issue because I'm reviewing the repositories that can be deleted. This content is really good and a lot of people still use it, so I'm going to keep it for now. According to the readme file message since MAY/2019: We won't do any maintenance, but I can (i can't guarantee) evaluate fix PRs. TKS!!
